DROP TABLE TEMP_ORDER_ID CASCADE CONSTRAINTS ; 

CREATE GLOBAL TEMPORARY TABLE TEMP_ORDER_ID (
  order_id	  int   NOT NULL
)
ON COMMIT PRESERVE ROWS;

ALTER TABLE TEMP_ORDER_ID ADD
CONSTRAINT PK_temp_order_id PRIMARY KEY  (order_id)
/

CREATE PUBLIC SYNONYM TEMP_ORDER_ID FOR TEMP_ORDER_ID; 