
DROP TABLE YA_ASSET CASCADE CONSTRAINTS ; 

CREATE TABLE YA_ASSET ( 
  ASSET_ID     NUMBER        NOT NULL, 
  DATA         NCLOB, 
  TYPE_ID      NUMBER        NOT NULL, 
  DESCRIPTION  NVARCHAR2 (1024))
   TABLESPACE SSCOMMERCESERVER_DATA NOLOGGING 
   NOCACHE; 


CREATE UNIQUE INDEX SYS_IL0000057621C00002$$ ON 
  YA_ASSET() 
  TABLESPACE SSCOMMERCESERVER_DATA
; 

ALTER TABLE YA_ASSET
 ADD CONSTRAINT YA_ASSET_PK
  PRIMARY KEY (ASSET_ID) 
  USING INDEX 
  TABLESPACE SSCOMMERCESERVER_DATA
; 



CREATE PUBLIC SYNONYM YA_ASSET FOR YA_ASSET;


GRANT SELECT ON YA_ASSET TO YS_WEB;
GRANT SELECT ON YA_ASSET TO YA_WEB;
GRANT SELECT ON YA_ASSET TO BO_YS;
GRANT SELECT ON YA_ASSET TO BO_US;
