
DROP TABLE YA_BLOCKINSTANCE_SETTING CASCADE CONSTRAINTS ; 

CREATE TABLE YA_BLOCKINSTANCE_SETTING ( 
  BLOCKTEMPLATE_ID  NUMBER        NOT NULL, 
  BLOCKINSTANCE_ID  NUMBER        NOT NULL, 
  SETTINGNAME       VARCHAR2 (255), 
  SETTINGVALUE      VARCHAR2 (255))
   TABLESPACE SSCOMMERCESERVER_DATA NOLOGGING 
   NOCACHE; 


CREATE PUBLIC SYNONYM YA_BLOCKINSTANCE_SETTING FOR YA_BLOCKINSTANCE_SETTING;

GRANT SELECT ON YA_BLOCKINSTANCE_SETTING TO YS_WEB;
GRANT SELECT ON YA_BLOCKINSTANCE_SETTING TO YA_WEB;
GRANT SELECT ON YA_BLOCKINSTANCE_SETTING TO BO_YS;
GRANT SELECT ON YA_BLOCKINSTANCE_SETTING TO BO_US;
