
DROP TABLE YA_BLOCKTEMPLATE CASCADE CONSTRAINTS ; 

CREATE TABLE YA_BLOCKTEMPLATE ( 
  BLOCKTEMPLATE_ID  NUMBER        NOT NULL, 
  NAME              VARCHAR2 (255), 
  CLASSNAME         VARCHAR2 (255), 
  EDITPAGENAME      VARCHAR2 (255))
   TABLESPACE SSCOMMERCESERVER_DATA NOLOGGING 
   NOCACHE; 


ALTER TABLE YA_BLOCKTEMPLATE
 ADD CONSTRAINT YA_BLOCKTEMPLATE_PK
  PRIMARY KEY (BLOCKTEMPLATE_ID) 
  USING INDEX 
  TABLESPACE SSCOMMERCESERVER_DATA
; 



CREATE PUBLIC SYNONYM YA_BLOCKTEMPLATE FOR YA_BLOCKTEMPLATE;

GRANT SELECT ON YA_BLOCKTEMPLATE TO YS_WEB;
GRANT SELECT ON YA_BLOCKTEMPLATE TO YA_WEB;
GRANT SELECT ON YA_BLOCKTEMPLATE TO BO_YS;
GRANT SELECT ON YA_BLOCKTEMPLATE TO BO_US;
