
DROP TABLE YA_BLOCKINSTANCE_ASSET_REL CASCADE CONSTRAINTS ; 

CREATE TABLE YA_BLOCKINSTANCE_ASSET_REL ( 
  BLOCKTEMPLATE_ID  NUMBER        NOT NULL, 
  BLOCKINSTANCE_ID  NUMBER        NOT NULL, 
  ASSET_ID          NUMBER        NOT NULL)
   TABLESPACE SSCOMMERCESERVER_DATA NOLOGGING 
   NOCACHE; 


CREATE PUBLIC SYNONYM YA_BLOCKINSTANCE_ASSET_REL FOR YA_BLOCKINSTANCE_ASSET_REL;

GRANT SELECT ON YA_BLOCKINSTANCE_ASSET_REL TO YS_WEB;
GRANT SELECT ON YA_BLOCKINSTANCE_ASSET_REL TO YA_WEB;
GRANT SELECT ON YA_BLOCKINSTANCE_ASSET_REL TO BO_YS;
GRANT SELECT ON YA_BLOCKINSTANCE_ASSET_REL TO BO_US;

