
DROP TABLE YA_PAGE CASCADE CONSTRAINTS ; 

CREATE TABLE YA_PAGE ( 
  PAGE_ID  NUMBER        NOT NULL, 
  SRC      VARCHAR2 (255))
   TABLESPACE SSCOMMERCESERVER_DATA NOLOGGING 
   NOCACHE; 


ALTER TABLE YA_PAGE
 ADD CONSTRAINT YA_PAGE_PK
  PRIMARY KEY (PAGE_ID) 
  USING INDEX 
  TABLESPACE SSCOMMERCESERVER_DATA 
; 



CREATE PUBLIC SYNONYM YA_PAGE FOR YA_PAGE;

GRANT SELECT ON YA_PAGE TO YS_WEB;
GRANT SELECT ON YA_PAGE TO YA_WEB;
GRANT SELECT ON YA_PAGE TO BO_YS;
GRANT SELECT ON YA_PAGE TO BO_US;
