
DROP TABLE YA_PAGE_LANG CASCADE CONSTRAINTS ; 

CREATE TABLE YA_PAGE_LANG ( 
  PAGE_ID       NUMBER        NOT NULL, 
  LANG_ID       NUMBER        NOT NULL, 
  TITLE         NVARCHAR2 (510), 
  META_DESC     NVARCHAR2 (1000), 
  META_KEYWORD  NVARCHAR2 (1000))
   TABLESPACE SSCOMMERCESERVER_DATA NOLOGGING 
   NOCACHE; 


CREATE PUBLIC SYNONYM YA_PAGE_LANG FOR YA_PAGE_LANG;

GRANT SELECT ON YA_PAGE_LANG TO YS_WEB;
GRANT SELECT ON YA_PAGE_LANG TO YA_WEB;
GRANT SELECT ON YA_PAGE_LANG TO BO_YS;
GRANT SELECT ON YA_PAGE_LANG TO BO_US;
