
DROP TABLE YA_PAGE_BLOCKINSTANCE CASCADE CONSTRAINTS ; 

CREATE TABLE YA_PAGE_BLOCKINSTANCE ( 
  PAGE_ID              NUMBER        NOT NULL, 
  SITE_ID              NUMBER        NOT NULL, 
  PLACEHOLDER_ID       NUMBER        NOT NULL, 
  BLOCKINSTANCE_ORDER  NUMBER        NOT NULL, 
  BLOCKTEMPLATE_ID     NUMBER        NOT NULL, 
  BLOCKINSTANCE_ID     NUMBER        NOT NULL)
   TABLESPACE SSCOMMERCESERVER_DATA NOLOGGING 
   NOCACHE; 


CREATE PUBLIC SYNONYM YA_PAGE_BLOCKINSTANCE FOR YA_PAGE_BLOCKINSTANCE;

GRANT SELECT ON YA_PAGE_BLOCKINSTANCE TO YS_WEB;
GRANT SELECT ON YA_PAGE_BLOCKINSTANCE TO YA_WEB;
GRANT SELECT ON YA_PAGE_BLOCKINSTANCE TO BO_YS;
GRANT SELECT ON YA_PAGE_BLOCKINSTANCE TO BO_US;
