DROP TABLE YA_PREFERRED_ATTR_LIST CASCADE CONSTRAINTS ; 

CREATE TABLE YA_PREFERRED_ATTR_LIST ( 
  PROD_LINE_ID     INT      NOT NULL, 
  ATTRIBUTE_ID     INT		NOT NULL 
)
/

ALTER TABLE YA_PREFERRED_ATTR_LIST
 ADD CONSTRAINT PK_YA_PREFERRED_ATTR_LIST
  PRIMARY KEY (PROD_LINE_ID,ATTRIBUTE_ID) 
/



CREATE PUBLIC SYNONYM YA_PREFERRED_ATTR_LIST FOR YA_PREFERRED_ATTR_LIST;


GRANT ALL ON YA_PREFERRED_ATTR_LIST TO YA_WEB;