drop materialized view vw_product_rating_approve
/

CREATE MATERIALIZED VIEW vw_product_rating_approve
  REFRESH COMPLETE ON DEMAND
    AS 
  SELECT YPR.RATING_ID RATING_ID,YPR.SKU SKU,YPR.PRODUCT_RATING PRODUCT_RATING,YPR.DATE_POSTED DATE_POSTED,YPR.SHOPPER_ID SHOPPER_ID,YPR.REVIEW_APPROVED REVIEW_APPROVED,YPR.REVIEWER_TYPE REVIEWER_TYPE,YPR.REVIEWER REVIEWER,YPR.ROWGUID ROWGUID FROM YA_PRODUCT_RATING YPR WHERE 1=1 AND YPR.REVIEW_APPROVED='I' AND YPR.REVIEWER_TYPE='USER'
/